-- MySQL Script generated by MySQL Workbench
-- Sun May 17 11:12:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idOfUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `photoLink` VARCHAR(45) NULL,
  PRIMARY KEY (`idOfUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `idOfPost` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(280) NULL,
  `createdAt` DATETIME NULL,
  `hashTags` VARCHAR(200) NULL,
  `likes` VARCHAR(200) NULL,
  `photoLink` VARCHAR(45) NULL,
  `idOfUser` INT NOT NULL,
  PRIMARY KEY (`idOfPost`),
  INDEX `fk_Posts_Users_idx` (`idOfUser` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Users`
    FOREIGN KEY (`idOfUser`)
    REFERENCES `mydb`.`Users` (`idOfUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hashTagsDB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hashTagsDB` (
  `idOfTag` INT NOT NULL AUTO_INCREMENT,
  `hashTag` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idOfTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hashTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hashTags` (
  `idOfHashTags` INT NOT NULL,
  `idOfTag` INT NOT NULL,
  `idOfPost` INT NOT NULL,
  PRIMARY KEY (`idOfHashTags`),
  INDEX `fk_hashTags_hashTagsDB1_idx` (`idOfTag` ASC) VISIBLE,
  INDEX `fk_hashTags_Posts1_idx` (`idOfPost` ASC) VISIBLE,
  CONSTRAINT `fk_hashTags_hashTagsDB1`
    FOREIGN KEY (`idOfTag`)
    REFERENCES `mydb`.`hashTagsDB` (`idOfTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hashTags_Posts1`
    FOREIGN KEY (`idOfPost`)
    REFERENCES `mydb`.`Posts` (`idOfPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `idOfLikes` INT NOT NULL,
  `idOfPost` INT NOT NULL,
  `idOfUser` INT NOT NULL,
  PRIMARY KEY (`idOfLikes`),
  INDEX `fk_likes_Posts1_idx` (`idOfPost` ASC) VISIBLE,
  INDEX `fk_likes_Users1_idx` (`idOfUser` ASC) VISIBLE,
  CONSTRAINT `fk_likes_Posts1`
    FOREIGN KEY (`idOfPost`)
    REFERENCES `mydb`.`Posts` (`idOfPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_Users1`
    FOREIGN KEY (`idOfUser`)
    REFERENCES `mydb`.`Users` (`idOfUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
